openapi: 3.0.0
info:
  version: '1.0'
  title: 'Employee Service API'
  description: 'This service provides information about employees'
  termsOfService: https://example.com/terms
  contact:
    name: Karthikeyan Nithiyanandam
    url: https://www.linkedin.com/in/karthikeyan-nithiyanandam/
    email: karthikeyan.ng@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers: 
  - url: https://dev.mysite.com
    description: Development Server
  - url: https://qa.mysite.com
    description: QA Server
  - url: https://prod.mysite.com
    description: Production Server 
paths:
  /v1/employess:
    get:
      responses:
        '200':
          description: List of Employees    
  /v1/beers:
    get:
      responses:
        '200':
          description: List of Beers
        '400':
          description: Not Found
